---
Resources:
  Nodegroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: ronyEKS
      NodegroupName: ronyNodegroup
      NodeRole: arn:aws:iam::388328004932:role/eks-node-group
      LaunchTemplate:
        Name: RonyLaunch
      ScalingConfig:
        MinSize: 1
        DesiredSize: 2
        MaxSize: 3
      Subnets:
        - subnet-0a31af885cfd8721d
        - subnet-01b356a04735bdf93
